// Code generated by "stringer -type=recordType"; DO NOT EDIT.

package copyist

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriverOpen-1]
	_ = x[ConnPrepare-2]
	_ = x[ConnBegin-3]
	_ = x[StmtNumInput-4]
	_ = x[StmtExec-5]
	_ = x[StmtQuery-6]
	_ = x[TxCommit-7]
	_ = x[TxRollback-8]
	_ = x[ResultLastInsertId-9]
	_ = x[ResultRowsAffected-10]
	_ = x[RowsColumns-11]
	_ = x[RowsNext-12]
}

const _RecordType_name = "DriverOpenConnPrepareConnBeginStmtNumInputStmtExecStmtQueryTxCommitTxRollbackResultLastInsertIdResultRowsAffectedRowsColumnsRowsNext"

var _RecordType_index = [...]uint8{0, 10, 21, 30, 42, 50, 59, 67, 77, 95, 113, 124, 132}

func (i recordType) String() string {
	i -= 1
	if i < 0 || i >= recordType(len(_RecordType_index)-1) {
		return "recordType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RecordType_name[_RecordType_index[i]:_RecordType_index[i+1]]
}
